version: '3.8'

services:
  frontend:
    container_name: frontend
    image : renishponkiya/si-front-app:latest
    environment:
      - VITE_API_URL=http://20.40.48.31:5000
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  backend:
    container_name: backend
    image : renishponkiya/si-back-app:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
    - ./backend/.env
    volumes:
      - sqlite_data:/app/backend/instance
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  sqlite_data: