version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - API_URL=http://20.124.89.94:5000
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_URL= http://20.124.89.94:80,http://localhost,http://20.124.89.94,http://20.40.48.31:80
      - GEMINI_API_KEY=AIzaSyCs-AJvdl5jUmSOgzSTRGfukX-jDhUoBZs
      - DATABASE_URL=sqlite:///site.db
      - FLASK_DEBUG=False
    volumes:
      - sqlite_data:/app/backend/instance
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  sqlite_data: