"""resume column created_At

Revision ID: 6b0fe6da967e
Revises: f108221204a6
Create Date: 2025-06-27 23:23:57.097772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0fe6da967e'
down_revision = 'f108221204a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_data', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
